"""replased marks with saved and unsaved

Revision ID: a5a5b4397a1f
Revises: dbd65d1203a9
Create Date: 2022-07-24 16:40:49.303383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a5b4397a1f'
down_revision = 'dbd65d1203a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('saved_marks', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('unsaved_marks', sa.String(), nullable=True))
    op.drop_column('subjects', 'marks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('marks', sa.VARCHAR(), nullable=True))
    op.drop_column('subjects', 'unsaved_marks')
    op.drop_column('subjects', 'saved_marks')
    # ### end Alembic commands ###
