"""deleted useless fields

Revision ID: dbd65d1203a9
Revises: 
Create Date: 2022-07-24 14:34:15.992355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd65d1203a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mos_ru_password')
    op.drop_column('users', 'mos_ru_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mos_ru_login', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('mos_ru_password', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
